// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (id, amount, note, created_at, goal_id, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    $3,
    $4
)
RETURNING id, amount, note, created_at, goal_id, user_id
`

type CreateDepositParams struct {
	Amount int32
	Note   sql.NullString
	GoalID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, createDeposit,
		arg.Amount,
		arg.Note,
		arg.GoalID,
		arg.UserID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
		&i.GoalID,
		&i.UserID,
	)
	return i, err
}
