// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, target, deadline, created_at, updated_at, user_id)
VALUES (
    get_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, target, deadline, created_at, updated_at, user_id
`

type CreateGoalParams struct {
	Target   int32
	Deadline time.Time
	UserID   uuid.UUID
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.Target, arg.Deadline, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
