// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, target, deadline, created_at, updated_at, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, target, deadline, created_at, updated_at, user_id
`

type CreateGoalParams struct {
	Target   int32
	Deadline time.Time
	UserID   uuid.UUID
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.Target, arg.Deadline, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, id)
	return err
}

const getGoalById = `-- name: GetGoalById :one
SELECT id, target, deadline, created_at, updated_at, user_id FROM goals
WHERE id = $1
`

func (q *Queries) GetGoalById(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalById, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
