// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, target, deadline, created_at, updated_at, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, target, deadline, created_at, updated_at, user_id
`

type CreateGoalParams struct {
	Target   int32
	Deadline time.Time
	UserID   uuid.UUID
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.Target, arg.Deadline, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoalById = `-- name: GetGoalById :one
SELECT id, target, deadline, created_at, updated_at, user_id FROM goals
WHERE id = $1
`

func (q *Queries) GetGoalById(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalById, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getGoals = `-- name: GetGoals :many
SELECT 
    goals.id,
    goals.target,
    goals.deadline,
    goals.created_at, 
    goals.updated_at,
    goals.user_id,
    COALESCE(SUM(deposits.amount), 0)::bigint as progress
FROM goals
LEFT JOIN deposits ON goals.id = deposits.goal_id
WHERE goals.user_id = $1
GROUP BY goals.id, goals.target, goals.deadline, goals.created_at, goals.updated_at, goals.user_id
`

type GetGoalsRow struct {
	ID        uuid.UUID
	Target    int32
	Deadline  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Progress  int64
}

func (q *Queries) GetGoals(ctx context.Context, userID uuid.UUID) ([]GetGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoalsRow
	for rows.Next() {
		var i GetGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET target = $1, deadline = $2, updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, target, deadline, created_at, updated_at, user_id
`

type UpdateGoalParams struct {
	Target   int32
	Deadline time.Time
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Target,
		arg.Deadline,
		arg.ID,
		arg.UserID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
