// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Deposit struct {
	ID        uuid.UUID
	Amount    int32
	Note      sql.NullString
	CreatedAt time.Time
	GoalID    uuid.UUID
	UserID    uuid.UUID
}

type Goal struct {
	ID        uuid.UUID
	Target    int32
	Deadline  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type PasswordResetToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	FullName       string
}
