// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens
SET consumed_at = NOW()
WHERE id = $1
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, consumePasswordResetToken, id)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens(id, user_id, token_hash, created_at, expires_at)
VALUES (
    GEN_RANDOM_UUID(),
    $1,
    $2,
    NOW(),
    NOW() + INTERVAL '30 minutes'
)
RETURNING id, user_id, token_hash, created_at, expires_at, consumed_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deactivateUserTokens = `-- name: DeactivateUserTokens :exec
UPDATE password_reset_tokens
SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) DeactivateUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateUserTokens, userID)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, created_at, expires_at, consumed_at FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
